- name: Ensure web root exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Download latest WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: "0644"

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    creates: /var/www/html/wordpress/wp-settings.php

- name: Copy wp-config-sample.php to wp-config.php
  copy:
    src: /var/www/html/wordpress/wp-config-sample.php
    dest: /var/www/html/wordpress/wp-config.php
    remote_src: yes

- name: Configure wp-config.php with shared DB + prefixes
  lineinfile:
    path: /var/www/html/wordpress/wp-config.php
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regex: "define\\( 'DB_NAME', '.*' \\);",   line: "define( 'DB_NAME', '{{ shared_db | default('shared_db') }}' );" }
    - { regex: "define\\( 'DB_USER', '.*' \\);",   line: "define( 'DB_USER', '{{ app_db_user | default('appuser') }}' );" }
    - { regex: "define\\( 'DB_PASSWORD', '.*' \\);", line: "define( 'DB_PASSWORD', '{{ app_db_pass | default('changeme') }}' );" }
    - { regex: "define\\( 'DB_HOST', '.*' \\);",   line: "define( 'DB_HOST', 'localhost' );" }
    - { regex: "^\\$table_prefix\\s*=\\s*'.*';",   line: "$table_prefix = 'wp_';" }
  notify: Reload Apache

- name: Ensure permissions on WordPress directory
  file:
    path: /var/www/html/wordpress
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: "0755"
